### ISSUE TITLE
Waypoints/SpawnPoint - Need Moving

### ISSUE THREAD

**Issue by Liam-Nagle** [Liam-Nagle/TowerDefenceGame#5]
Waypoints can't be seen/moved and the waypoints path is incorrect because of this. 

The only fix I can see is creating new waypoints and moving them. But maybe something with Sorting Layers fixes this? @TankDS 

Will leave this for you.

**Comment by TankDS** [comment]
Negative co-ordinates in the Z axis meant the waypoint were not visible in 2D view for moving. Changed all waypoint objects to 0 and correctly moved X & Y to line up with path on tilegrid. Spawn point also corrected.
