### ISSUE TITLE
Tower Selection

### ISSUE THREAD

**Issue by TankDS** [Liam-Nagle/TowerDefenceGame#8]
Currently able to select a tower (highlight it) and select a second tower (also highlights). Whilst the backend updates the tower currently in hand for placement, UI highlights both towers regardless.

Implement code to highlight ONLY the most recently selected tower.

```
void SpawnTower(Vector3 position)
	{
		GameObject tower = Instantiate(towersPrefabs[spawnID], spawnTowerRoot);
		tower.transform.position = position;
		DeselectTowers();
	}

	public void SelectTower(int id)
	{
		//Set the spawnID
		spawnID = id;
		//Highlight the tower
		towersUI[spawnID].color = Color.white;
	}

	public void DeselectTowers()
	{
		spawnID = -1;
		foreach (var t in towersUI)
		{
			t.color = new Color(0.5f, 0.5f, 0.5f);
		}
	}
```

**Comment by Liam-Nagle** [comment]
Will need you to talk me through the towers code more later. Might be best to make some "Generic" tower Image to test if that's the cause? From the brief bit of code pasted it looks as though some code somewhere isn't calling DeselectTowers() correctly

**Comment by Liam-Nagle** [comment]
Just checked and now understand the issue. In the "SelectTower" function you need an IF statement to check if a tower is currently selected. If it is.. Deselect that tower

**Comment by Liam-Nagle** [comment]
Fixed. Added DeslectTowers() at the start of the SelectTower() Function to deselect any other tower selected

**Comment by TankDS** [comment]
Changes not pushed to branch. Implemented DeselectTowers() at the start of SelectTower() method and pushed changes to rectify bug.
